# Generated by Django 4.2.6 on 2024-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_profile_photo_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
