# Generated by Django 4.2.6 on 2024-11-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='espesializasaun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
