# Generated by Django 4.2.6 on 2024-11-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_espesializasaun'),
        ('registo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registo',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_registrations', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='registo',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Konsulta Hela', 'Konsulta Hela'), ('Konsulta Hotu ona', 'Konsulta Hotu ona')], default='Pendente', max_length=20),
        ),
    ]
